// ============================================================
// models/Board.js
// Mongoose schema for a BlackBoard board document.
// Each board stores lock settings (date, password, or both),
// the collaborative text content, whiteboard data, and
// expiration settings.
// ============================================================

const mongoose = require('mongoose');

const boardSchema = new mongoose.Schema({
  // ---------------------------------------------------------
  // boardId — short, URL-friendly unique identifier
  // Generated by nanoid in the controller before saving.
  // Indexed as unique so lookups are fast.
  // ---------------------------------------------------------
  boardId: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    index: true,
  },

  // ---------------------------------------------------------
  // boardName — optional human-readable name for the board.
  // ---------------------------------------------------------
  boardName: {
    type: String,
    default: 'Untitled Board',
    trim: true,
  },

  // ---------------------------------------------------------
  // content — the actual text/content of the board.
  // Starts empty; updated via Socket.io real-time events.
  // ---------------------------------------------------------
  content: {
    type: String,
    default: '',
  },

  // ---------------------------------------------------------
  // unlockType — determines which lock mechanism is active.
  //   'date'     → unlocks after a specific datetime
  //   'password' → unlocks with the correct password
  //   'both'     → requires BOTH date AND password
  // ---------------------------------------------------------
  unlockType: {
    type: String,
    enum: ['date', 'password', 'both'],
    required: true,
  },

  // ---------------------------------------------------------
  // unlockAt — the datetime after which a date-locked board
  // becomes accessible.  Only required for 'date' and 'both'.
  // ---------------------------------------------------------
  unlockAt: {
    type: Date,
    default: null,
  },

  // ---------------------------------------------------------
  // passwordHash — bcrypt hash of the board password.
  // NEVER sent to the frontend; compared server-side only.
  // Only set for 'password' and 'both' types.
  // ---------------------------------------------------------
  passwordHash: {
    type: String,
    default: null,
  },

  // ---------------------------------------------------------
  // Expiration fields — link expires X hours after first unlock
  // ---------------------------------------------------------
  activatedAt: {
    type: Date,
    default: null,
  },

  expiresAfter: {
    type: Number,
    default: 3,
    min: 1,
    max: 48,
  },

  isExpired: {
    type: Boolean,
    default: false,
  },

  // ---------------------------------------------------------
  // images — URLs of images uploaded to the text board
  // ---------------------------------------------------------
  images: {
    type: [String],
    default: [],
  },

  // ---------------------------------------------------------
  // attachedImages — URLs of images uploaded during board creation
  // ---------------------------------------------------------
  attachedImages: {
    type: [String],
    default: [],
  },

  // ---------------------------------------------------------
  // whiteboardData — stores strokes and image data for the
  // collaborative whiteboard canvas.
  // ---------------------------------------------------------
  whiteboardData: {
    type: Array,
    default: [],
  },

  // ---------------------------------------------------------
  // createdAt — timestamp of board creation (set by default).
  // ---------------------------------------------------------
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Export the model so it can be imported in controllers/routes.
module.exports = mongoose.model('Board', boardSchema);
